const $=id=>document.getElementById(id);let state,currentCity,currentWeather;
const icons={Clear:'☀',Sunny:'☀','Mainly clear':'🌤','Partly cloudy':'⛅',Overcast:'☁',Fog:'≋','Light rain':'🌦','Moderate rain':'🌧','Heavy rain':'🌧','Light snow':'🌨','Moderate snow':'❄',Thunderstorm:'⛈'};
const ui={en:{language:'Language',places:'PLACES',cities:'Your cities',feels:'Feels like',humidity:'Humidity',wind:'Wind',pressure:'Pressure',outlook:'OUTLOOK',forecast:'Seven-day forecast',play:'Play weather',local:'Local',favorite:'Favorite'},zh:{language:'语言',places:'城市',cities:'我的城市',feels:'体感温度',humidity:'湿度',wind:'风速',pressure:'气压',outlook:'未来天气',forecast:'七天天气预报',play:'播放天气',local:'当前位置',favorite:'收藏'},fr:{language:'Langue',places:'LIEUX',cities:'Vos villes',feels:'Ressenti',humidity:'Humidité',wind:'Vent',pressure:'Pression',outlook:'PRÉVISIONS',forecast:'Prévisions sur sept jours',play:'Écouter la météo',local:'Position',favorite:'Favori'},es:{language:'Idioma',places:'LUGARES',cities:'Tus ciudades',feels:'Sensación',humidity:'Humedad',wind:'Viento',pressure:'Presión',outlook:'PRONÓSTICO',forecast:'Pronóstico de siete días',play:'Escuchar el tiempo',local:'Ubicación',favorite:'Favorita'},ja:{language:'言語',places:'場所',cities:'都市',feels:'体感温度',humidity:'湿度',wind:'風速',pressure:'気圧',outlook:'予報',forecast:'7日間予報',play:'天気を再生',local:'現在地',favorite:'お気に入り'}};
function applyLanguage(){const t=ui[state.language]||ui.en;$('language-label').textContent=t.language;$('places-label').textContent=t.places;$('cities-heading').textContent=t.cities;$('feels-label').textContent=t.feels;$('humidity-label').textContent=t.humidity;$('wind-label').textContent=t.wind;$('pressure-label').textContent=t.pressure;$('outlook-label').textContent=t.outlook;$('forecast-heading').textContent=t.forecast;$('speak').textContent=`▶ ${t.play}`;document.documentElement.lang=state.language}
const showToast=message=>{const el=$('toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)};
const api=async(url,options)=>{const r=await fetch(url,options);const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');return d};
const cityName=c=>state.language==='zh'&&c.zh?c.zh:c.city;
function renderCities(){const root=$('cities');root.innerHTML='';const t=ui[state.language]||ui.en;state.cities.forEach((c,i)=>{const b=document.createElement('button');b.className='city-button'+(currentCity===c.city?' active':'');b.innerHTML=`<span class="city-icon">${c.local?'⌖':'☆'}</span><span class="city-label"><strong>${cityName(c)}</strong><small>${c.local?t.local:t.favorite}</small></span>`;b.onclick=()=>{if(c.unset)return showToast('Set your location in voice-weather-cli settings');loadCity(c.city)};root.appendChild(b)})}
function weatherIcon(desc){return icons[desc]||'◌'}
async function loadCity(city){currentCity=city;renderCities();$('hero').classList.add('loading-card');try{const lang=state.language;const [now,outlook]=await Promise.all([api(`/api/weather?city=${encodeURIComponent(city)}&language=${lang}`),api(`/api/forecast?city=${encodeURIComponent(city)}&language=${lang}&days=7`)]);currentWeather=now.weather;renderWeather(now);renderForecast(outlook.forecast)}catch(e){showToast(e.message)}finally{$('hero').classList.remove('loading-card')}}
function renderWeather(data){const w=data.weather;$('city-name').textContent=data.city;$('condition').textContent=w.description_localized;$('weather-icon').textContent=weatherIcon(w.description);$('temperature').textContent=`${w.temperature_c}°`;$('feels').textContent=`${w.feels_like_c}°`;$('humidity').textContent=`${w.humidity}%`;$('wind').textContent=`${w.wind_kph} km/h`;$('pressure').textContent=`${w.pressure_hpa} hPa`;$('local-time').textContent=w.local_time.replace('T',' · ')}
function renderForecast(days){$('forecast').innerHTML=days.map(d=>{const date=new Date(`${d.date}T12:00:00`);return `<div class="forecast-day"><div class="day">${date.toLocaleDateString(undefined,{weekday:'short'})}</div><div class="symbol">${weatherIcon(d.description)}</div><div class="range">${d.max_c}° <span style="color:var(--muted)">${d.min_c}°</span></div><div class="rain">♢ ${d.rain_chance}%</div></div>`}).join('')}
async function init(){try{state=await api('/api/state');$('version').textContent=`Version ${state.version} · local web app`;$('language').innerHTML=Object.entries(state.languages).map(([k,v])=>`<option value="${k}" ${k===state.language?'selected':''}>${v}</option>`).join('');$('voice-status').textContent=state.voice?`Voice: ${state.voice}`:'Text only';applyLanguage();renderCities();const first=state.cities.find(c=>!c.unset);if(first)loadCity(first.city)}catch(e){showToast(e.message)}}
$('language').onchange=async e=>{await api('/api/preferences',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({language:e.target.value})});state.language=e.target.value;applyLanguage();renderCities();if(currentCity)loadCity(currentCity)};
$('refresh').onclick=()=>currentCity&&loadCity(currentCity);$('add-city').onclick=()=>{const city=prompt('City and country');if(city)loadCity(city)};
$('speak').onclick=async()=>{if(!currentWeather)return;const text=`${currentCity}. ${currentWeather.description_localized}. ${currentWeather.temperature_c} degrees.`;try{await api('/api/speak',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,language:state.language})});showToast('Playing weather')}catch(e){showToast(e.message)}};
init();
